export type CriterionState = "MET" | "NOT_MET" | "UNKNOWN" | "NEEDS_REVIEW" | "DECLINED" | "not_addressed" | "claimed" | "described" | "corroborated" | "deferred";

export interface Job { job_id: string; title: string; basic_qualifications: string[]; }
export interface Criterion { criterion_id: string; job_id: string; label: string; priority: "required" | "valued"; kind: string; competency_id: string | null; display_order: number; suggested_question: string | null; deferred: boolean; }
export interface Evidence { evidence_id: string; candidate_id: string; source_kind: string; source_author: string; quote: string; statement: string; competency_ids: string[]; strength: string; ownership: string; review_state: string; drafted_by: string; }
export interface CandidateSummary { candidate_id: string; short_code: string; full_name: string; arrival_time: string; roles_of_interest: string[]; }
export interface CandidateDetail extends CandidateSummary { email: string; phone: string; school: string; confirmed_facts: Record<string,string>; resume_text: string; profile: Record<string,any>; scan_complete: boolean; recruiter_ratings: any[]; checklist_ratings: any[]; spill_notes: any[]; preferences: any[]; matches: any[]; conversation_starters?: string[]; evidence: Evidence[]; states_by_job: Record<string,{states:{criterion_id:string;state:CriterionState;basis_ids:string[]}[];explore_next:{criterion_id:string;state:CriterionState;question:string|null}[]}>; decisions: any[]; audit: any[]; }
export interface DatabaseStatus { connected: boolean; engine: string; database_file: string; journal_mode: string; foreign_keys: boolean; schema_tables: number; required_tables: number; missing_tables: string[]; counts: { candidates: number; jobs: number; recruiter_ratings: number; spill_notes: number; match_results: number; shortlist_decisions: number; audit_events: number; }; }
export interface Bootstrap { jobs: Job[]; criteria: Criterion[]; candidates: CandidateSummary[]; hero_candidate_id: string; study: { lists: string[]; case_count: number }; matching: any; database: DatabaseStatus; }
export interface Draft { quote: string; statement: string; competency_ids: string[]; strength: "claimed"|"described"; ownership: "individual"|"team"|"unclear"; }
